### ISSUE TITLE
Not all required tables created in sql/create.sql

### ISSUE THREAD

**Issue by nmonarizqa** [Bus-Data-NYC/nyc-bus-stats#1]
Hi Neil, 

In the Makefile, `make init` and `make init-month` are supposed to load data into some tables such as `schedule` (line 156) and `ref_holidays` (line 184). However, I couldn't find lines indicating that these tables are created in `sql/create.sql` so those data can't be inserted. Is there something I am missing here?

**Comment by fitnr** [comment]
Those errors reflect a renaming and a datapoint that I created manually. Fixed.
