### ISSUE TITLE
hw_gtfs

### ISSUE THREAD

**Issue by nmonarizqa** [Bus-Data-NYC/nyc-bus-stats#3]
In `make cewt`, `missing_calls` table need to be joined with `hw_gtfs`, but when executed, the table is empty. I tracked the sql and apparently, the values are inserted in `sql/headway_sched.sql` line 45. However, it returns an error because there is no `ref_date_trips` (line 25) table created before. Any help would be greatly appreciated!

**Comment by fitnr** [comment]
Somehow `ref_date_trips` wasn't in `create.sql`. I just pushed a commit that adds it ([3a26b](https://github.com/Bus-Data-NYC/nyc-bus-stats/commit/3a26bec45e7510dfda725d7beccbcbdae8e72575)).

The code in `sql/date_trips.sql` will populate the table. It uses a stored procedure to loop through all the possible dates in a given date range and add a row to the table for every (date, trip_index) pair. Make sure the table `start_date` has your desired date range and then run `mysql < sql/date_trips.sql`.
